syms m h g b v vd phi phid phidd delta deltad real;
EOM = m*h*v^2*tan(delta)/l - m*g*h*sin(phi) + m*h*phidd ...
    + m*b*vd*tan(delta)/l - m*h^2*v^2*(tan(delta))^2*tan(phi)/l ...
    + m*b*h*phid*v*tan(delta)*tan(phi)/l + b*deltad*h*m*v/(l*(cos(delta))^2);
simplify(EOM/h/m)